listening-ip=0.0.0.0
listening-port=3478
tls-listening-port=5349
fingerprint
lt-cred-mech
realm=${TURN_REALM}
user=${TURN_USERNAME}:${TURN_PASSWORD}
external-ip=${TURN_PUBLIC_IP}
min-port=49160
max-port=49200
allowed-peer-ip=0.0.0.0-255.255.255.255
cert=/etc/letsencrypt/live/${SIGNALING_DOMAIN}/fullchain.pem
pkey=/etc/letsencrypt/live/${SIGNALING_DOMAIN}/privkey.pem
no-multicast-peers
log-file=/var/log/turnserver.log
no-stdout-log
